### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by EdricChan03** [probot/commands#10]
Will there be TypeScript support for `probot-commands`?

Since `create-probot-app` supports the `typescript` option, Probot apps can now be created with TypeScript.

**Comment by hiimbex** [comment]
I'd love to see TS support for all the probot extension, but it's not high on our priority list right now.

We'd happily review PRs in the meantime to add support for types. :)

**Comment by EdricChan03** [comment]
Hey @hiimbex! Looks like @fd has opened a PR to address this very issue: #15 

It would be great if you could review and merge that PR!

**Comment by Laurianti** [comment]
Similar issues:
#19
#22

**Comment by Laurianti** [comment]
The support was created but not merged, why?

The support was done in this PRs
https://github.com/probot/commands/pull/15
https://github.com/probot/commands/pull/20
