### ISSUE TITLE
Should handle cases where issue/pr body is null

### ISSUE THREAD

**Issue by tcbyrd** [probot/commands#9]
Sentry [reported an error](https://sentry.io/probot/reminders/issues/600255998/) this morning on this line because an issue body was null:

https://github.com/probot/commands/blob/641358cf00dad74d5f5a15636631eaaf33e84128/index.js#L14

Even though an issue/pr comment body would not be null if it contains a command, bots still have to listen for `on('issues.opened')` events, and those bodies can be null. This should return early if the body is not null<sup>[1]</sup>

<sub>[1]</sub> 🙏 [optional chaining](https://github.com/tc39/proposal-optional-chaining#optional-chaining-for-javascript)

**Comment by chrishiestand** [comment]
Looks like this PR got dropped, when it should have been merged? https://github.com/probot/commands/pull/13
